project_name: appbuilder

release:
  github:
    owner: choria-io
    name: appbuilder
  name_template: "Release {{.Version}}"
  draft: true

changelog:
  disable: true

builds:
  - ldflags:
    - "-s -w -X github.com/choria-io/appbuilder/builder.Version={{.Version}} -X github.com/choria-io/appbuilder/builder.Commit={{.Commit}} -X github.com/choria-io/appbuilder/builder.Date={{.Date}}"
    id: appbuilder
    binary: appbuilder
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - name_template: "appbuilder-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

brews:
  - name: appbuilder
    directory: Formula
    repository:
      owner: choria-io
      name: homebrew-tap
    url_template: "https://github.com/choria-io/appbuilder/releases/download/{{ .Tag }}/appbuilder-{{.Version}}-{{ .Os }}-{{ .Arch }}{{if .Arm}}{{.Arm}}{{end}}.tar.gz"
    homepage: "https://github.com/choria-io/appbuilder"
    description: "Choria Application Builder"
    skip_upload: false
    test: |
      system "#{bin}/appbuilder --version"
    install: |
      bin.install "appbuilder"
      bin.install_symlink "appbuilder" => "abt"

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

nfpms:
  - file_name_template: 'appbuilder-{{.Version}}-{{ if eq .Arch "amd64" }}x86_64{{ else}}{{.Arch}}{{end}}{{if .Arm}}{{.Arm}}{{end}}'
    homepage:  https://github.com/choria-io/appbuilder
    description: Choria App Builder CLI
    maintainer: R.I. Pienaar <rip@devco.net>
    license: Apache 2.0
    vendor: Choria
    bindir: /usr/bin
    formats:
      - deb
      - rpm
    contents:
      - dst: /etc/appbuilder
        type: dir

      - dst: /usr/bin/abt
        src: /usr/bin/appbuilder
        type: symlink