baseURL = "https://choria-io.github.io/appbuilder/"
languageCode = "en-us"
title = "Choria Application Builder Documentation"
theme = "hugo-theme-relearn"

[outputFormats.TXT]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true

[outputs]
home = [ "html", "rss", "print", "markdown", "txt"]
section = [ "html", "rss", "print", "markdown"]
page = [ "html",  "print", "markdown"]

[author]
name = "Choria Project"

[params]
showVisitedLinks = false
disableLanguageSwitchingButton = true
disableInlineCopyToClipBoard = true
alwaysopen = true
externalLinkTargetc= "_self"

[[params.themeVariant]]
    auto = ['zen-light', 'ccm']
    identifier = 'zen-auto'
    name = 'Auto Theme'

    [[params.themeVariant]]
        identifier = 'zen-light'
        name = 'Light'

    [[params.themeVariant]]
        identifier = 'ccm'
        name = 'Dark'

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/choria-io/appbuilder"
weight = 10

[[menu.shortcuts]]
name = "<i class='far fa-save'></i> Download"
url = "https://github.com/choria-io/appbuilder/releases"
weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-comments'></i> Discussions"
url = "https://github.com/choria-io/appbuilder/discussions"
weight = 12

[[menu.shortcuts]]
name = "<i class='far fa-life-ring'></i> Issues"
url = "https://github.com/choria-io/appbuilder/issues"
weight = 13

[[menu.shortcuts]]
name = "<i class='fab fa-slack'></i> #choria"
url = "https://short.voxpupu.li/puppetcommunity_slack_signup"
weight = 14
