baseURL = "https://choria-io.github.io/appbuilder/"
languageCode = "en-us"
title = "Choria Application Builder Documentation"
theme = "hugo-theme-relearn"
canonifyURLs = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
author = "Choria Project"
showVisitedLinks = false
disableLanguageSwitchingButton = true
themeVariant = "my-custom-variant"
disableInlineCopyToClipBoard = true
alwaysopen = true

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/choria-io/appbuilder"
weight = 10

[[menu.shortcuts]]
name = "<i class='far fa-download'></i> Download"
url = "https://github.com/choria-io/appbuilder/releases"
weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-comments'></i> Discussions"
url = "https://github.com/choria-io/appbuilder/discussions"
weight = 12

[[menu.shortcuts]]
name = "<i class='far fa-life-ring'></i> Issues"
url = "https://github.com/choria-io/appbuilder/issues"
weight = 13

[[menu.shortcuts]]
name = "<i class='fab fa-slack'></i> #choria"
url = "https://slack.puppet.com/"
weight = 14
