name: Unit Tests
on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        go: [ "1.22", "1.23" ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Lint and Test
        uses: choria-io/actions/lint_and_test/go@main
        with:
          ginkgo: "v2"
